FROM ghcr.io/mafrosis/informa:dev

# Install lint, test tools
COPY requirements-dev.txt /src
RUN pip install -r requirements-dev.txt

COPY .pylintrc /src

RUN apt-get update && apt-get install -y git

# Generate mypy type stubs for third party packages
RUN mkdir /tmp/stubs && \
	git clone --depth=1 https://github.com/fake-useragent/fake-useragent.git /tmp/stubs/fake-useragent && \
	cd /tmp/stubs/fake-useragent/src/fake_useragent && \
		stubgen -v -p fake_useragent -o /mypy-stubs && \
	git clone --depth=1 https://github.com/kurtmckee/feedparser.git /tmp/stubs/feedparser && \
	cd /tmp/stubs/feedparser && \
		stubgen -v -p feedparser -o /mypy-stubs && \
	rm -rf /tmp/stubs

ENTRYPOINT ["pytest"]
