# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mafrosis/jessie64-gb-salt"

  # create a shared dir in /tmp
  config.vm.synced_folder "/tmp", "/tmp/host_machine"

  # setup the salt-minion
  config.vm.provision :salt do |salt|
    salt.minion_config = "salt-minion.conf"
    salt.run_highstate = false
  end
end
